### ISSUE TITLE
Credential Leackage

### ISSUE THREAD

**Issue by SamoraMachel** [WilliamOtieno/InstaBot#1]
https://github.com/WilliamOtieno/InstaBot/blob/67cadaa3973039e9b1b1cb51ff181b833f07542f/main.py#L4
https://github.com/WilliamOtieno/InstaBot/blob/67cadaa3973039e9b1b1cb51ff181b833f07542f/main.py#L26
https://github.com/WilliamOtieno/InstaBot/blob/67cadaa3973039e9b1b1cb51ff181b833f07542f/secrets.py#L1

## Data Leakage 
You cannot Expose your credentials on a the on the web like so. 
**This is a security flaw of which hackers can easily mine your data.**
> It would be wiser if you use some little bit of encryption 
> cause this is  a very big app flaw if you plan on creating 
> an full featured Instagram bot or when creating simple scripts

you can use modules like **``` encryption and pickle ```** to 
slightly counter this flaw.
For the moment, it would be better if you  hide this repository 
cause your Instagram account is at risk

**Comment by WilliamOtieno** [comment]
The bot is actually incomplete. I'll refactor the code and do the changes. Thanks
